plugins {
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.kotlinAndroid)
}

import java.util.Properties
import java.io.FileInputStream

android {
    namespace = "com.wing.folderplayer"
    compileSdk = 34

    // Load keystore properties
    val keystorePropertiesFile = rootProject.file("keystore.properties")
    val keystoreProperties = Properties()
    if (keystorePropertiesFile.exists()) {
        keystoreProperties.load(FileInputStream(keystorePropertiesFile))
    }

    signingConfigs {
        create("release") {
            if (keystoreProperties.isNotEmpty()) {
                storeFile = rootProject.file(keystoreProperties["storeFile"] as String)
                storePassword = keystoreProperties["storePassword"] as String
                keyAlias = keystoreProperties["keyAlias"] as String
                keyPassword = keystoreProperties["keyPassword"] as String
            }
        }
    }

    defaultConfig {
        // Fork identity: installs side by side with the original com.wing.folderplayer.
        applicationId = "com.wing.folderplayer.fork"
        minSdk = 26
        targetSdk = 34
        // CI passes the tag as version (-PfpVersionName=0.5.1 -PfpVersionCode=...); local builds use the defaults.
        versionCode = (project.findProperty("fpVersionCode") as String?)?.toInt() ?: 501
        versionName = (project.findProperty("fpVersionName") as String?) ?: "0.5.0-fork.1"
        resValue("string", "app_name", "Folder Player Fork")

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        ndk {
            // arm64-v8a is the device target; x86_64 lets emulators run the JNI path.
            abiFilters += listOf("arm64-v8a", "x86_64")
        }
        vectorDrawables {
            useSupportLibrary = true
        }
    }

    buildTypes {
        release {
            // No R8 shrinking: SMBJ, jUPnP, Ktor and Gson rely on reflection/ServiceLoader, and the release must run
            // exactly the code the tests ran.
            isMinifyEnabled = false
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
            // Signed only when keystore.properties exists (local file or written by CI from secrets).
            signingConfig = if (keystoreProperties.isNotEmpty()) signingConfigs.getByName("release") else null
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
        // jUPnP / SMBJ use java.time and newer collection APIs that are missing below API 26..33.
        isCoreLibraryDesugaringEnabled = true
    }
    kotlinOptions {
        jvmTarget = "1.8"
    }
    buildFeatures {
        compose = true
        buildConfig = true
    }
    testOptions {
        unitTests.isReturnDefaultValues = true
        unitTests.all {
            // Protocol integration tests read fixture endpoints from system properties (see scripts/fixtures/).
            it.systemProperties(System.getProperties().filterKeys { k -> k.toString().startsWith("fp.") }.mapKeys { e -> e.key.toString() })
        }
    }
    composeOptions {
        kotlinCompilerExtensionVersion = "1.5.1"
    }
    // Languages are switched in-app, so every locale must stay in the base APK.
    bundle {
        language { enableSplit = false }
    }
    // Decoder fixtures (generated by scripts/fixtures/make_fixture.py) ship inside the test APK only.
    sourceSets["androidTest"].assets.srcDir(rootProject.file("build/fixture/android-test-assets"))
    ndkVersion = "28.2.13676358"
    externalNativeBuild {
        cmake {
            path = file("src/main/cpp/CMakeLists.txt")
            version = "3.22.1"
        }
    }
    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
            excludes += "/META-INF/versions/9/OSGI-INF/MANIFEST.MF"
            excludes += "/META-INF/INDEX.LIST"
            excludes += "/META-INF/DEPENDENCIES"
            excludes += "/META-INF/io.netty.versions.properties"
        }
    }
}

dependencies {

    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.activity.compose)
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.ui)
    implementation(libs.androidx.ui.graphics)
    implementation(libs.androidx.ui.tooling.preview)
    implementation(libs.androidx.material3)
    implementation(libs.androidx.material.icons.extended)
    implementation(libs.androidx.navigation.compose)
    implementation(libs.androidx.datastore.preferences)

    // Guava & Coroutines
    implementation(libs.guava)
    implementation(libs.kotlinx.coroutines.guava)

    // Media3
    implementation(libs.androidx.media3.exoplayer)
    implementation(libs.androidx.media3.session)
    implementation(libs.androidx.media3.ui)
    implementation(libs.androidx.media3.common)
    implementation(libs.androidx.media3.extractor)
    implementation(libs.androidx.media3.datasource.okhttp)

    // Image Loading
    implementation(libs.coil.compose)

    // Network
    implementation(libs.retrofit)
    implementation(libs.converter.gson)
    implementation(libs.gson)
    implementation(libs.okhttp)
    implementation(libs.okhttp.urlconnection)
    
    // Network sources: SMB (SMBJ) and FTP/FTPS (Apache Commons Net)
    implementation(libs.smbj)
    // Share list (srvsvc NetShareEnumAll over IPC$) for the SMB editor; BSD-3-Clause, Rapid7. Uses the SMBJ above.
    // Guava stays the project's Android build (the JRE build it asks for would replace it).
    implementation(libs.smbj.dcerpc) { exclude(group = "com.google.guava", module = "guava") }
    implementation(libs.commons.net)
    implementation(libs.slf4j.nop)

    // DLNA control point (jUPnP) and the on-device HTTP relay (Ktor CIO)
    implementation(libs.jupnp.core)
    implementation(libs.jupnp.support)
    implementation(libs.ktor.server.core)
    implementation(libs.ktor.server.cio)

    implementation(libs.androidx.documentfile)
    coreLibraryDesugaring(libs.desugar.jdk.libs)

    // Audio Metadata - TEMPORARILY DISABLED FOR TESTING
    // implementation(libs.jaudiotagger)
    
    testImplementation(libs.junit)
    testImplementation(libs.kotlinx.coroutines.test)
    testImplementation(libs.okhttp.mockwebserver)
    testImplementation(libs.json.org)
    androidTestImplementation(libs.androidx.test.core)
    androidTestImplementation(libs.androidx.test.rules)
    androidTestImplementation(libs.androidx.test.runner)
    androidTestImplementation(libs.androidx.test.uiautomator)
    androidTestImplementation(libs.okhttp.mockwebserver)
    androidTestImplementation(libs.kotlinx.coroutines.test)
    androidTestImplementation(libs.androidx.junit)
    androidTestImplementation(libs.androidx.espresso.core)
    androidTestImplementation(platform(libs.androidx.compose.bom))
    androidTestImplementation(libs.androidx.ui.test.junit4)
    debugImplementation(libs.androidx.ui.tooling)
    debugImplementation(libs.androidx.ui.test.manifest)
}

// FFmpeg static libraries are rebuilt from the pinned source tarball when missing (Linux/WSL with the NDK).
val buildFfmpeg by tasks.registering(Exec::class) {
    val out = rootProject.file("native/out")
    onlyIf { !File(out, "arm64-v8a/lib/libavcodec.a").exists() || !File(out, "x86_64/lib/libavcodec.a").exists() }
    workingDir = rootProject.projectDir
    commandLine("bash", "native/build-ffmpeg.sh")
}
tasks.matching { it.name.startsWith("configureCMake") || it.name.startsWith("buildCMake") }.configureEach { dependsOn(buildFfmpeg) }

// Prints the unit-test runtime classpath so protocol tests that need the Docker network (DLNA multicast) can run
// inside a JVM container: scripts/fixtures/run-in-network-tests.sh
tasks.register("printUnitTestClasspath") {
    // The FileCollection carries the build dependencies of its jars/class dirs (not of the test task itself).
    val cp = tasks.named<Test>("testDebugUnitTest").get().classpath
    dependsOn(cp)
    doLast { println("CP=" + cp.asPath) }
}
